#TRIGGER
name: CI-CD Pipeline
on:
  #MANUAl TRIGGER
  workflow_dispatch:
  #TIGGER ON PUSH BRANCH MASTER
  push:
    branch:
      - master

#DEFINE JOBS:
jobs:
  #1ST JOB TESTING
  test:
    name: Unit Testing
    #RUNNER
    runs-on: self-hosted
    #JOB STEP
    steps:
      # checkout repo
      - uses: actions/checkout@v3
      # set up JDK
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      # set up maven cache
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Run Test
      - name: Run Tests
        run:
          mvn clean verify

  #2ND JOB BUILD PROJECT
  build:
    needs: test
    name: Build and Run
    runs-on: self-hosted
    # job steps
    steps:
      # checkout repo under $github_workspace, accesible by workflow
      - uses: actions/checkout@v3
      # set up JDK
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      # set up maven cache
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Run Build Package if Runner Windows:
      - name: Run Build Package
        run:
          mvn clean package `-Dmaven.test.skip=true
      # run project
      - name: Run Project
        shell: cmd
        run:
          start run.bat
#      # Run Build Package if Runner Linux:
#      - name: Run Build Package
#        run:
#          mvn clean package -Dmaven.test.skip=true
